//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class HandControllerAdapter : MonoBehaviour
	{

		public HandController handController;
		private int assetIndex;

		public void AdaptedPlayRecording(TextAsset asset){
			handController.StopRecording ();
			handController.PlayRecording ();
		}

		public void AdaptedRecord(){
			handController.Record ();
		}

		public void AdaptedResetRecording(){
			handController.ResetRecording ();
		}


		public void AdaptedFinishAndSaveRecording(Action<string> callback){
			string output = handController.FinishAndSaveRecording ();
			callback (output);
		}

		public void AdaptedGetHandParent(Action<Transform> callback){
			Transform handParent = handController.handParent;
			callback(handParent);
		}

		public void AdaptedSetHandParent(Transform parent){
			handController.handParent = parent;
		}
		public void AdaptedTrackingEnabled(bool isEnabled){
			handController.DestroyAllHands();
			handController.gameObject.SetActive (isEnabled);
		}

	}
}

